### ISSUE TITLE
Crash : Library bug 

### ISSUE THREAD

**Issue by 13120241790** [yedona/PickPhoto#1]
Hi ~ 
Method ：startForPickGalleryPhotoAndZoom 

2021-04-12 18:28:00.117 9494-9494/com.yedona.pickphoto E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.yedona.pickphoto, PID: 9494
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=android:fragment:1, request=27840, result=-1, data=Intent { dat=content://com.yedona.pickphoto.yedona.provider/external_storage_root/DCIM/Camera/IMG_20200518_165318.jpg (has extras) }} to activity {com.yedona.pickphoto/com.yedona.pickphoto.MainActivity}: java.lang.IllegalArgumentException: column '_data' does not exist. Available columns: []
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5112)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5153)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2227)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:230)
        at android.app.ActivityThread.main(ActivityThread.java:7748)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:508)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
     Caused by: java.lang.IllegalArgumentException: column '_data' does not exist. Available columns: []
        at android.database.AbstractCursor.getColumnIndexOrThrow(AbstractCursor.java:352)
        at android.database.CursorWrapper.getColumnIndexOrThrow(CursorWrapper.java:91)
        at com.yedona.takephoto.utils.UriUtils.getDataColumn(UriUtils.java:103)
        at com.yedona.takephoto.utils.UriUtils.getPath(UriUtils.java:82)
        at com.yedona.takephoto.utils.PhotoZoomUtils$1.onActivityResult(PhotoZoomUtils.java:67)
        at com.yedona.takephoto.avoidresult.AvoidOnResultFragment.onActivityResult(AvoidOnResultFragment.java:55)
        at android.app.Activity.dispatchActivityResult(Activity.java:8216)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5105)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5153) 
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2227) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 

Device : iQOO vivo Android 10

**Comment by yedona** [comment]
已更换Uri获取方式
